var tree_node=new Array(0,"工时汇总","工时汇总","","","",3,"","","",-1,2,"工时汇总","工时汇总","","",4,"t_clicked(\"/remuneration_set/list\");","","",2,"庭审和调解","庭审和调解","","",4,"t_clicked(\"/remuneration1_set/list\");","","",2,"阅卷信息","阅卷信息","","",4,"t_clicked(\"/remuneration2_set/list\");","","",2,"仲裁员仲裁报酬","仲裁员仲裁报酬","","",4,"t_clicked(\"/remuneration3_set/list\");","","",2,"助理程序处理","助理程序处理","","",4,"t_clicked(\"/remuneration6_set/list\");","","",2,"调查取证","调查取证","","",4,"t_clicked(\"/remuneration8_set/list\");","","",2,"助理发文量","助理发文量","","",4,"t_clicked(\"/remuneration9_set/list\");","","",2,"裁决书和管辖决定等的起草和修改","裁决书和管辖决定等的起草和修改","","",4,"t_clicked(\"/remuneration4_set/list\");","","",2,"校核工作","校核工作","","",4,"t_clicked(\"/remuneration5_set/list\");","","",2,"仲裁报酬奖惩信息","仲裁报酬奖惩信息","","",4,"t_clicked(\"/bonus_penalty/list\");","","",2,"奖励、扣减","奖励、扣减","","",4,"t_clicked(\"/deduct/list\");","","",2,"仲裁报酬汇总信息","仲裁报酬汇总信息","","",4,"t_clicked(\"/remuneration_sum/list\");","","",2,"案件扣除时段","案件扣除时段","","",4,"t_clicked(\"/remuneration_time_less_set/list\");","","",2,"报酬报表","报酬报表","","",4,"t_clicked(\"/remuneration_set_report_a/list\");","","",1,5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=true;
tree.Indent=13;
tree.folderImg1="TREEIMG/tree_Lplus.gif";
tree.lineFolder="TREEIMG/";
tree.folderImg2="TREEIMG/tree_Lminus.gif";
tree.fileImg="TREEIMG/tree_Lplus.gif";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
