var tree_node=new Array(0,"报酬","报酬","","","",4,"","","",-1,2,"办案其它报酬_案件","办案其它报酬_案件","","",4,"t_clicked(\"/remuneration23_set/list\");","","",2,"办案其它报酬_独立维护","办案其它报酬_独立维护","","",4,"t_clicked(\"/remuneration23_set2/list\");","","",2,"案件报酬","案件报酬","","",4,"t_clicked(\"/extend/list\");","","",2,"报酬发放","报酬发放","","",4,"t_clicked(\"/t_extend/list\");","","",2,"报酬发放信息","报酬发放信息","","",4,"t_clicked(\"/show_extend/list_extend_code\");","","",2,"短信提醒信息","短信提醒信息","","",4,"t_clicked(\"/sms_alert/list\");","","",2,"已发短信提醒信息","已发短信提醒信息","","",4,"t_clicked(\"/sms_alert/list_1\");","","",1,5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=false;
tree.Indent=13;
tree.folderImg1="";
tree.lineFolder="./";
tree.folderImg2="";
tree.fileImg="";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
