var tree_node=new Array(0,"财务","财务","","","",3,"","","",-1,2,"案件费用统计","案件费用统计","","",4,"t_clicked(\"/report_total2/list\");","","",2,"受理案件仲裁条款及争议金额分析","受理案件仲裁条款及争议金额分析","","",4,"t_clicked(\"/report_total3/list\");","","",2,"仲裁员费用情况","仲裁员费用情况","","",4,"t_clicked(\"/report_total2/list_1\");","","",2,"仲裁员人案统计","仲裁员人案统计","","",4,"t_clicked(\"/census3/list3_9\");","","",2,"结案查询","结案查询","","",4,"t_clicked(\"/census3/list3_6\")","","",2,"撤案查询","撤案查询","","",4,"t_clicked(\"/census3/list3_7\")","","",2,"案件财务平衡表","案件财务平衡表","","",4,"t_clicked(\"/finance_balance/case_list_1\")","","",2,"立结审案件数统计","立结审案件数统计","","",4,"t_clicked(\"/census3/list3_34\")","","",1,5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=true;
tree.Indent=13;
tree.folderImg1="TREEIMG/tree_Lplus.gif";
tree.lineFolder="TREEIMG/";
tree.folderImg2="TREEIMG/tree_Lminus.gif";
tree.fileImg="TREEIMG/tree_Lplus.gif";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
