mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3000.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3001.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3002.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3003.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3004.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3005.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3006.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3007.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3008.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3009.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3010.pid
mongrel_rails stop -P /usr/local/zc/log/mongrel_pid/mongrel_3011.pid
